### ISSUE TITLE
Products can't generate more than 100 products

### ISSUE THREAD

**Issue by myworkpool** [metorikhq/wc-cyclone#10]
Hello ,

Your plugin is great, really love.

By the way, I can't create a product over 100 units, it always struck at 98 or 100 units.

I'm not sure it's a bug or anything.

// second test, it can be reach over 100 products , but in case that no picture on it.

**Comment by bryceadams** [comment]
Hi! It's likely due to the lack of demo data to create more at once. I'll try add more in the future. Thanks, glad you like it! :)
