### ISSUE TITLE
Adding Orders Eats Up Disk Space in MySQL

### ISSUE THREAD

**Issue by devinsays** [metorikhq/wc-cyclone#14]
So, weird thing. Generating 100 orders takes about 3 minutes and eats up about 6GB of disk space in MySQL. After running `wp db optimize` it clears out. Not sure if this is specific to my install (could be something having to do with Subscriptions enabled?) or happens on all installs.

Just creating a holder ticket for this, I'll look into it further.

**Comment by devinsays** [comment]
Tracked down the issue! Apparently MySQL8 creates a binary log of all the writes made to the database: https://dev.mysql.com/doc/refman/8.0/en/binary-log.html. That was the real culprit!

**Comment by bryceadams** [comment]
Ah, better to stick to MariaDB haha. Thanks for the update :)
