### ISSUE TITLE
Seed command failing?

### ISSUE THREAD

**Issue by lmartins** [metorikhq/wc-cyclone#7]
Hi,

I was trying to setup cyclone on a new site and have gone through the process described in this project's repo. That includes install composer depend. before enabling the plugin.

Once I've done that I've tried to set the `seed` by running `wp cyclone seed --type=books` which responds with `We are going to download a collection of images from Unsplash now. Please be patient...` But that command ends immediately and doesn't seem to download any image.

If I then try to run `wp cyclone products 10` I get the error:

```
Error: You need to seed data first. Please run `wp cyclone seed --type=books` where type is either books or food to get started.
```
I've also tried to pass a new unsplash App ID but no luck. What might be going wrong?

**Comment by bryceadams** [comment]
Hey! Sorry I didn't see this until now @lmartins. How about just `wp cyclone seed`?
