### ISSUE TITLE
Open to contributions?

### ISSUE THREAD

**Issue by rayrutjes** [metorikhq/wc-cyclone#9]
Hi @bryceadams ,

First of all, thanks for recommending your plugin, I'm using it since I tried it.

I was willing to contribute a bit in the future for some features that I need (product variants, attributes generation). Would that be of any interest to you?

Also, I was wondering if you was willing to keep this WooCommerce focused only or if you would be inclined to accept WordPress only related generators. The plugin I used until now: FakerPress is kinda becoming more broken on every new WP release, and I think you have a good boilerplate where I could plug some features onto.

Let me know what you had in mind for this repo ;)

**Comment by bryceadams** [comment]
100% would love those extra features you worked on! I've needed them too so
that will be great.

For the WordPress general features, that's a good question. Maybe it would
be good to have? I can't see the harm in adding it. What kinda stuff did
you do, posts/comments/etc.?

Thanks Raymond! :)

**Comment by rayrutjes** [comment]
For the WooCommerce side, so far what I could really use and will probably implement soon is:
- generate attributes (select|text)
- add random attributes to products
- generate product variants
- generate product tags & categories
- attach product tags & categories to product

For WordPress, it is mainly posts with featured image + tag + category.

I'll close this for now and come back with a PR as soon as I have something ;)

**Comment by bryceadams** [comment]
Awesome, can't wait! :)
